//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecepcionTelefonicaAuditoriaDeEstados
    {
        public decimal IdRT { get; set; }
        public System.DateTime FechaHora { get; set; }
        public System.Guid Operador { get; set; }
        public string R1Estado { get; set; }
    }
}
