//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecepcionTelefonica
    {
        public decimal IdRT { get; set; }
        public Nullable<decimal> R1IdServicioLS { get; set; }
        public Nullable<System.DateTime> FhLlamada { get; set; }
        public Nullable<short> NroLlamado { get; set; }
        public string CuandoSiniestro { get; set; }
        public Nullable<short> IdTipoSiniestro { get; set; }
        public Nullable<bool> Lesionado { get; set; }
        public Nullable<bool> DenunciaPolicial { get; set; }
        public Nullable<bool> Llaves { get; set; }
        public Nullable<short> IdDepartamentoSiniestro { get; set; }
        public string BarrioSiniestro { get; set; }
        public string CalleSiniestro { get; set; }
        public string NroPuertaSiniestro { get; set; }
        public string EsquinaSiniestro { get; set; }
        public string RutaSiniestro { get; set; }
        public Nullable<short> KilometroSiniestro { get; set; }
        public Nullable<decimal> LatitudSiniestro { get; set; }
        public Nullable<decimal> LongitudSiniestro { get; set; }
        public string TipoBusquedaSiniestro { get; set; }
        public bool SeguroBse { get; set; }
        public bool Circula { get; set; }
        public Nullable<short> CantidadVehiculos { get; set; }
        public Nullable<bool> Rectificacion { get; set; }
        public string TipoAsistencia { get; set; }
        public string SubZona { get; set; }
        public Nullable<bool> Programado { get; set; }
        public Nullable<System.DateTime> FhProgramada { get; set; }
        public Nullable<short> IdLugarPreEstablecido { get; set; }
        public Nullable<short> IdDepartamentoConcurrencia { get; set; }
        public string BarrioConcurrencia { get; set; }
        public string CalleConcurrencia { get; set; }
        public string NroPuertaConcurrencia { get; set; }
        public string EsquinaConcurrencia { get; set; }
        public string RutaConcurrencia { get; set; }
        public Nullable<short> KilometroConcurrencia { get; set; }
        public Nullable<decimal> LatitudConcurrencia { get; set; }
        public Nullable<decimal> LongitudConcurrencia { get; set; }
        public string TipoBusquedaConcurrencia { get; set; }
        public string ReferenciaUbicacion { get; set; }
        public string MatriculaDenunciante { get; set; }
        public Nullable<short> IdTipoVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public string MatriculaContraParte1 { get; set; }
        public string MarcaContraParte1 { get; set; }
        public string ModeloContraParte1 { get; set; }
        public string ColorContraParte1 { get; set; }
        public string MatriculaContraParte2 { get; set; }
        public string MarcaContraParte2 { get; set; }
        public string ModeloContraParte2 { get; set; }
        public string ColorContraParte2 { get; set; }
        public string ObsContraPartes { get; set; }
        public string NombreLlama { get; set; }
        public string TelefonoLlamo { get; set; }
        public string NombreConductor { get; set; }
        public string TelefonoConductor { get; set; }
        public string ObservacionesLlamado { get; set; }
        public Nullable<System.DateTime> R1FhMaxima { get; set; }
        public Nullable<short> TiempoAtencion { get; set; }
        public string R1Estado { get; set; }
        public Nullable<System.Guid> IdUsuarioRecepciono { get; set; }
        public Nullable<System.Guid> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaHoraModificacion { get; set; }
        public string PlanNew { get; set; }
        public Nullable<System.DateTime> FechaHoraAsignado { get; set; }
        public Nullable<int> MovilAsignado { get; set; }
        public Nullable<System.DateTime> FechaHoraLLegada { get; set; }
        public Nullable<int> Demora { get; set; }
        public Nullable<int> Tarde { get; set; }
        public Nullable<System.DateTime> FechaHoraFinalizo { get; set; }
        public Nullable<int> TiempoAsistencia { get; set; }
        public string Situacion { get; set; }
        public Nullable<int> CantidadDePartes { get; set; }
        public Nullable<System.Guid> ConcurreAbogado { get; set; }
        public Nullable<System.Guid> Operador { get; set; }
        public Nullable<System.DateTime> FechaHoraUltimaModificacionOperador { get; set; }
        public Nullable<int> FotosSinDenunciante { get; set; }
        public Nullable<int> Testigos { get; set; }
        public Nullable<int> SiniestrosReclamacionesVarias { get; set; }
        public Nullable<bool> ConcurreAbogadoSiNo { get; set; }
        public string DatosAbogado { get; set; }
        public string ObservacionesAbogado { get; set; }
        public Nullable<System.DateTime> FechaHoraLLamadaAbogado { get; set; }
        public Nullable<System.DateTime> FechaHoraLLegadaAbogado { get; set; }
        public Nullable<System.Guid> IdUsuarioQueConvocaAlAbogado { get; set; }
        public bool ConcurreMovil { get; set; }
        public Nullable<int> IdMotivoCancelacionRT { get; set; }
    }
}
